name: Update kernel images

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 'debian:bullseye'
    
    steps: 
    - name: update apt
      run: apt-get update
      
    - name: kernel version check
      run: apt-cache search linux-image
    
    
      
